## Repaso Numpy y Pandas

1. Crea un array de 5x2 con los valores desde 100 hasta 200 de 10 en 10

In [2]:
import numpy as np
array = np.arange(100,201,10)

2. Redimensiona el array a 3x3 (se debe de eliminar el último elemento)

In [28]:
if array[-1] == 190: array = array[0:-1]

array = array.reshape(3,3)
print(array)

[[100 110 120]
 [130 140 150]
 [160 170 180]]


3. Crea un array con los elementos de la tercera posición de cada fila

In [34]:
array2 = array[:,2]
print(array2)

[120 150 180]


4. Muestra los elementos de las filas de posición par y columna de posición impar

In [38]:
array[0::2,1::2]

array([[110],
       [170]])

5. Crea dos arrays de 2x3. Posteriormente suma los dos arrays y a su resultado eleva al cuadrado cada elemento

In [41]:
array1 = np.random.randint(1,200,(2,3))
array2 = np.random.randint(1,200,(2,3))
print(array1)
print(array2)

resultado = array1 + array2
resultado **= 2
resultado

[[ 64 193  18]
 [ 55  94 189]]
[[106  62  14]
 [ 90  43  65]]


array([[28900, 65025,  1024],
       [21025, 18769, 64516]])

6. Crea un array de 8x3. Posteriormente dividelo en 4 subarrays

In [42]:
array4 = np.random.randint(1,200,(8,3))
array4.reshape(6,4)

array([[143, 103, 114,  83],
       [133,  91, 152, 104],
       [ 42,   2, 145,  83],
       [ 77, 196,  51, 186],
       [154, 183, 109,  58],
       [160,  81, 160,  82]])

7. Dado un array de 3x3. Crea un nuevo array con este ordenado por la 2ª fila y otro array con este array ordenado por la 2ª columna

In [76]:
array5 = np.random.randint(1,200,(3,3))
print(array5)
print()

array2f = array5.copy()
array2f[1,:] = np.sort(array2f[1,:])

print(array2f)
print()

array2c = array5.copy()
array2c[:,1] = np.sort(array2c[:,1])

print(array2c)

[[159 197  90]
 [ 29 154 120]
 [ 29  20   1]]

[[159 197  90]
 [ 29 120 154]
 [ 29  20   1]]

[[159  20  90]
 [ 29 154 120]
 [ 29 197   1]]


8. Dado un array de 3x3. Devuelve sus mínimos de cada columna y el máximo de cada fila

In [3]:
import pandas as pd

array6 = np.random.randint(1,200,(3,3))
df = pd.DataFrame(array6)
print(df)

minC = pd.Series(df.min(axis=0))
maxF = pd.Series(df.max(axis=1))
df["Max Fila"] = maxF
df.loc["Min Col"] = minC

df

     0   1   2
0   28  81  59
1  102  22   6
2  178  12  54


0     1     2  Max Fila
0         28.0  81.0  59.0      81.0
1        102.0  22.0   6.0     102.0
2        178.0  12.0  54.0     178.0
Min Col   28.0  12.0   6.0       NaN

9. Dado un array de 3x3 elimina su 2ª columna y añadela al inicio

In [122]:
df2 = pd.DataFrame(np.random.randint(1,200,(3,3)))
print(df2)

#Obtneros la serie que queremos poner al principio
primC = df2.iloc[:,1]

#Eliminamos la columna que ya tenemos
df2 = df2.drop(columns=1)

#Ponemos al principio
df2.insert(0,"1",primC)
df2


     0   1    2
0  153  99  178
1  149  17   61
2  141   9  172


1    0    2
0  99  153  178
1  17  149   61
2   9  141  172

10. Crea un DataFrame con la información de *coches.csv*

In [4]:
coches = pd.read_csv("coches.csv")
coches

11. Muestra la compañía que tenga el coche más caro

In [132]:
coches[coches.price == coches.price.max()].company

35    mercedes-benz
Name: company, dtype: object

12. Muestra todos los coches de Toyota

In [134]:
coches[coches.company == "toyota"]

index company body-style  wheel-base  length engine-type num-of-cylinders  \
48     66  toyota  hatchback        95.7   158.7         ohc             four   
49     67  toyota  hatchback        95.7   158.7         ohc             four   
50     68  toyota  hatchback        95.7   158.7         ohc             four   
51     69  toyota      wagon        95.7   169.7         ohc             four   
52     70  toyota      wagon        95.7   169.7         ohc             four   
53     71  toyota      wagon        95.7   169.7         ohc             four   
54     79  toyota      wagon       104.5   187.8        dohc              six   

    horsepower  average-mileage    price  
48          62               35   5348.0  
49          62               31   6338.0  
50          62               31   6488.0  
51          62               31   6918.0  
52          62               27   7898.0  
53          62               27   8778.0  
54         156               19  15750.0

13. Muestra cuántos coches tiene cada compañía

In [136]:
coches.groupby(["company"])["company"].count()

company
alfa-romero      3
audi             4
bmw              6
chevrolet        3
dodge            2
honda            3
isuzu            3
jaguar           3
mazda            5
mercedes-benz    4
mitsubishi       4
nissan           5
porsche          3
toyota           7
volkswagen       4
volvo            2
Name: company, dtype: int64

14. Muestra todas las compañías con su precio más caro

In [140]:
coches.groupby(["company"])[["company","price"]].agg({"price":np.max})

price
company               
alfa-romero    16500.0
audi           18920.0
bmw            41315.0
chevrolet       6575.0
dodge           6377.0
honda          12945.0
isuzu           6785.0
jaguar         36000.0
mazda          18344.0
mercedes-benz  45400.0
mitsubishi      8189.0
nissan         13499.0
porsche        37028.0
toyota         15750.0
volkswagen      9995.0
volvo          13415.0

15. Calcula la media de kilometros de cada compañía

16. Ordena los coches por precio