# Ejercicios ndarra


In [2]:
import numpy as np
#1. Define un ndarray de una dimensión con los valores 5,8 y 9.
array1 = np.array([5,8,9])

[5 8 9]


In [3]:
#2. Muestra su tamaño.
array1.size

3

In [4]:
#3. Muestra el dtype.
array1.dtype

dtype('int32')

In [6]:
#4. Define un ndarray con tres dimensiones y de tipo float usando como valores 5,8 y 9.
array2 = np.array(array1, dtype=float,ndmin=3)
print(array2)

[[[5. 8. 9.]]]


In [10]:
#5. Define tres ndarray el primer con ceros, el segundo con unos y el último con todo vacío. Todos ellos de una dimensión con tres columnas.
ceros = np.zeros((3))
print(ceros)
unos = np.ones((3))
#unos = np.zeros((3))+1
print(unos)
vacio = np.empty((3))
print(vacio)

[0. 0. 0.]
[1. 1. 1.]
[1. 1. 1.]


# Operaciones básicas con ndarray

In [12]:
#1. Define un ndarray con dos filas y dos columnas con los valores [1,2] y [3,6].
array1 = np.array([[1,2],[3,6]], dtype=int)

In [13]:
#2. Define otro ndarray con dos filas y dos columnas con los valores [6,6] y [7,7].
array2 = np.array([[6,6],[7,7]], dtype=int)

In [14]:
#3. Multiplica el ndarray del Ejercicio 1 con el del Ejercicio 2 y almacénalo en otra variable.
array3 = array1 * array2
print(array3)

[[ 6 12]
 [21 42]]


In [15]:
#4. Suma el ndarray del Ejercicio 1 con el del Ejercicio 2.
print(array1 + array2)

[[ 7  8]
 [10 13]]


In [16]:
#5. Suma 999 a cada elemento del ndarray del Ejercicio 1.
print(array1+999)

[[1000 1001]
 [1002 1005]]


# Ejercicios indexación y slicing

In [17]:
#1. Define un ndarray de una dimensión con los valores 100, 1, 1001 y 123.
array1 = np.array([100,1,1001,123])

array([ 100,    1, 1001,  123])

In [21]:
#2. Muestra los valores desde el primer elemento hasta el cuarto incluido.
print(array1[0:])

[ 100    1 1001  123]


In [20]:
#3. Muestra el valor de la primera posición.
print(array1[0])

100


In [31]:
#4. Define un ndarray con dos filas y cuatro columnas con los valores [1,1,1,1] y [2,2,2,2].
array2 = np.array([np.ones(4),np.ones(4)+1],dtype=int)
array2

array([[1, 1, 1, 1],
       [2, 2, 2, 2]])

In [32]:
#5. Muestra los dos primeros valores.
array2[:,0]

array([1, 2])

In [33]:
#6. Muestra el valor de la primera fila y primera columna.
array2[0,0]

1

In [34]:
#7. Muestra los valores que sean mayores que 1.
array2[array2>1]

array([2, 2, 2, 2])

# Ejercicios de funciones y métodos

In [36]:
#1. Defina un ndarray de una dimensión con los valores 100, 999, 998, 997 y 997.
array1 = np.array([100,999,998,997,997])

In [41]:
#2. Encuentra dónde está 997.
index = np.where(array1 == 997)[0]
print(index)

[3 4]


In [42]:
#3. Modifica todos los valores menores de 999 a 9999.
array1[array1 <  999] = 9999
print(array1)

[9999  999 9999 9999 9999]


In [43]:
#4. Obtén los valores únicos del ndarray.
print(np.unique(array1))

[ 999 9999]


In [51]:
#5. Devuelve True si todos los valores son mayores que 1000.
print(np.min(array1) > 1000)

False


In [49]:
#6. Devuelve True si algún valor es mayor que 1000.
print(np.max(array1) > 1000)

True


In [52]:
#7. Muestra los valores que sean mayores que 1.
print(array1[array1 > 1])

[9999  999 9999 9999 9999]
