## Ejercicios repaso Numpy

In [4]:
import numpy as np

1. Crea un vector de ceros de 10 elementos excepto el quinto elemento que debe de ser 1

In [6]:
array1 = np.zeros(10)
array1[4] = 1

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

2. Crea un vector con los valores desde el 10 hasta 49

In [23]:
array2 = np.arange(10,50)

3. Modifica el vector del ejercicio anterior y calcula el inverso

In [44]:
from numpy.linalg import inv
array2 = array2.reshape(2,20)


LinAlgError: 1-dimensional array given. Array must be at least two-dimensional

4. Crea una matriz de 3x3 con los valores desde 0 hasta 8

In [7]:
array3 = np.arange(0,9).reshape(3,3)
array3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

5. Crea una matriz de identidad de 4x4

In [7]:
arrayIdent = np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

6. Crea una matriz de 5x5x5 con valores aleatorios

In [49]:
arrayRand = np.random.rand(5,5,5)
print(arrayRand)

[[[0.38379524 0.11645953 0.20917057 0.91413921 0.87325987]
  [0.55169815 0.64519938 0.23770988 0.29935183 0.12554064]
  [0.63067591 0.93803635 0.55461108 0.47613328 0.6797356 ]
  [0.87935445 0.98999991 0.7608539  0.33938421 0.70034447]
  [0.12357793 0.31741721 0.83024077 0.45199159 0.54780263]]

 [[0.97002878 0.17902297 0.43806133 0.36533978 0.93299541]
  [0.82435433 0.14376552 0.24429981 0.54852228 0.15577524]
  [0.14520482 0.81109515 0.17844875 0.99950271 0.51646919]
  [0.4883108  0.92549407 0.9853177  0.51789891 0.63140226]
  [0.29745747 0.91026752 0.71352022 0.30764145 0.36651866]]

 [[0.78180635 0.68609118 0.99964534 0.45511866 0.85429382]
  [0.43795623 0.38752923 0.9338834  0.23424766 0.6353706 ]
  [0.5155848  0.4322127  0.86869428 0.21919232 0.45996138]
  [0.92662265 0.1978778  0.93707869 0.73602944 0.38994278]
  [0.57589833 0.5950483  0.90609493 0.09181725 0.77084627]]

 [[0.14461292 0.9551749  0.76460478 0.76817534 0.41394205]
  [0.03554909 0.32533767 0.26710203 0.28513314 0.8

7. Calcula la media del vector anterior

In [50]:
np.mean(arrayRand)

0.5530067362376061

8. Crea una matriz 3x3 con los valores 1,2,3 en la diagonal (el resto de elementos deben de ser 0)

In [59]:
arrayDiag = np.diagflat(np.arange(1,4))
print(arrayDiag)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


9. Crea una matriz 4x4 con los valores 1,2,3 en la diagonal inferior (el resto de elementos deben de ser 0)
[[0, 0, 0, 0],
[1, 0, 0, 0],
[0, 2, 0, 0],
[0, 0, 3, 0]]

In [64]:
arrayDiag = np.diagflat(np.arange(1,4),-1)
print(arrayDiag)

[[0 0 0 0]
 [1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]]


10. Normaliza una matriz de 4x4 con valores aleatorios

11. Multiplica una matriz de 6x3 (todos valores a 1) por una de 3x2 (todos valores a 1)

12. Realiza la multiplicación del ejercicio anterior utilizando un operador

13. Cree una matriz de 1 dimensión con los valores desde 1 a 10, con los valores desde 3 hasta 8 en negativo. [1, 2 , -3, -4, -5, -6, -7, -8, 9, 10]

14. Cree un vector de 10 elementos con los valores aleatorios entre 0 y 10

15. Cree un vector con todas las fechas de abril de 2022

16. Crea un vector ordenado de 15 elementos con valores aleatorios entre 1 y 10

17. Devuelva la suma de los valores del vector del ejercicio anterior

18. Devuelve el resultado de la suma del vector ejercicio 16 de una forma más rápida que utilizar np.sum

19. Crea un vector aleatorio de tamaño 20 y reemplaza el máximo valor por 0

20. Itera un numpy arrays mostrando su posición y el valor

21. Resta a cada elemento la media calculada de su fila de la matriz

22. Crea una matriz de 6x6 y ordenala por la 4ª fila

23. Existiendo el vector [1, 2, 3, 4, 5], construir un nuevo vector con 3 ceros consecuitovs entre cada valor del vector anterior

24. Crea un vector con números aleatorios de 5x5 e intercambia la fila segunda por la tercera