## Ejercicios repaso Numpy

In [2]:
import numpy as np

1. Crea un vector de ceros de 10 elementos excepto el quinto elemento que debe de ser 1

In [6]:
array1 = np.zeros(10)
array1[4] = 1

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

2. Crea un vector con los valores desde el 10 hasta 49

In [103]:
array2 = np.arange(10,50)
array2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

3. Modifica el vector del ejercicio anterior y calcula el inverso

In [117]:
def calcularInversa(array):
    array = modificarMatriz(array)

    if np.linalg.det(array) == 0:
        return "No se puede calcular la inversa"
    else:
        return np.linalg.inv(array)

def modificarMatriz(array):
    np.random.shuffle(array)
    return array[:36].reshape(6,6)

print(calcularInversa(array2))

[[ 0.01514429  0.01799232 -0.01050182 -0.015889   -0.00854138  0.00616762]
 [-0.0213417   0.04906769 -0.04419464 -0.00964394  0.03734955 -0.00539264]
 [-0.00123891 -0.02651243  0.0633945   0.00753421 -0.03507141 -0.00479705]
 [-0.00888379  0.05116152 -0.07717284  0.02306779  0.03463945 -0.00696152]
 [ 0.00166242 -0.0644174   0.04116922  0.00175344 -0.01572132  0.03125544]
 [ 0.02032463 -0.02867574  0.03507304 -0.0028538  -0.00679288 -0.01039599]]


4. Crea una matriz de 3x3 con los valores desde 0 hasta 8

In [7]:
array3 = np.arange(0,9).reshape(3,3)
array3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

5. Crea una matriz de identidad de 4x4

In [7]:
arrayIdent = np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

6. Crea una matriz de 5x5x5 con valores aleatorios

In [3]:
arrayRand = np.random.rand(5,5,5)
print(arrayRand)

[[[0.05025192 0.59437445 0.15116371 0.34988394 0.79835562]
  [0.88810673 0.19970177 0.51920972 0.92661343 0.8172862 ]
  [0.44040592 0.84423367 0.60822229 0.49634354 0.18018999]
  [0.72825474 0.49791176 0.94288928 0.97213863 0.38615536]
  [0.16052038 0.00664136 0.04063998 0.43321554 0.64816623]]

 [[0.20910667 0.15270517 0.09224586 0.66165747 0.86758789]
  [0.53699919 0.64812883 0.76376323 0.77995654 0.8166926 ]
  [0.39055557 0.78173321 0.0391665  0.82101362 0.07243274]
  [0.21079844 0.06436044 0.75044066 0.98278573 0.18030563]
  [0.16059155 0.23675728 0.94179651 0.11606374 0.00667005]]

 [[0.30368922 0.48819726 0.52872549 0.38712357 0.04283421]
  [0.39733723 0.54436227 0.04284701 0.96769214 0.74760982]
  [0.41663932 0.34408749 0.89894127 0.89859703 0.12980626]
  [0.24295009 0.41387425 0.08384883 0.90310959 0.93685889]
  [0.63268068 0.36784765 0.44003662 0.41693983 0.73770573]]

 [[0.42931907 0.68487881 0.54910377 0.62158664 0.19951335]
  [0.31616424 0.54563202 0.7677836  0.09464093 0.2

7. Calcula la media del vector anterior

In [4]:
np.mean(arrayRand)

0.4859684143647981

8. Crea una matriz 3x3 con los valores 1,2,3 en la diagonal (el resto de elementos deben de ser 0)

In [5]:
arrayDiag = np.diagflat(np.arange(1,4))
print(arrayDiag)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


9. Crea una matriz 4x4 con los valores 1,2,3 en la diagonal inferior (el resto de elementos deben de ser 0)
[[0, 0, 0, 0],
[1, 0, 0, 0],
[0, 2, 0, 0],
[0, 0, 3, 0]]

In [64]:
arrayDiag = np.diagflat(np.arange(1,4),-1)
print(arrayDiag)

[[0 0 0 0]
 [1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]]


10. Normaliza una matriz de 4x4 con valores aleatorios

In [74]:
np.linalg.norm(np.random.rand(4,4))

2.331623812133402

11. Multiplica una matriz de 6x3 (todos valores a 1) por una de 3x2 (todos valores a 1)

In [109]:
a = np.ones((6,3),dtype=int)
b = np.ones((3,2),dtype=int)
np.dot(a,b)


array([[3, 3],
       [3, 3],
       [3, 3],
       [3, 3],
       [3, 3],
       [3, 3]])

12. Realiza la multiplicación del ejercicio anterior utilizando un operador

In [110]:
print(a @ b)

[[3 3]
 [3 3]
 [3 3]
 [3 3]
 [3 3]
 [3 3]]


13. Cree una matriz de 1 dimensión con los valores desde 1 a 10, con los valores desde 3 hasta 8 en negativo. [1, 2 , -3, -4, -5, -6, -7, -8, 9, 10]

In [106]:
array2 = np.arange(1,11)
array2[(array2 >= 3) & (array2 <= 8)] *= -1
print(array2)


array([ 1,  2, -3, -4, -5, -6, -7, -8,  9, 10])

14. Cree un vector de 10 elementos con los valores aleatorios entre 0 y 10

In [108]:
arrayRand = np.random.randint(0,11,(10))
print(arrayRand)

array([ 3,  0,  2,  2, 10,  7,  1,  5,  1,  9])

15. Cree un vector con todas las fechas de abril de 2022

In [125]:
fechas = np.arange('2022-04', '2022-05',dtype='datetime64[D]')
print(fechas)

array(['2022-04-01', '2022-04-02', '2022-04-03', '2022-04-04',
       '2022-04-05', '2022-04-06', '2022-04-07', '2022-04-08',
       '2022-04-09', '2022-04-10', '2022-04-11', '2022-04-12',
       '2022-04-13', '2022-04-14', '2022-04-15', '2022-04-16',
       '2022-04-17', '2022-04-18', '2022-04-19', '2022-04-20',
       '2022-04-21', '2022-04-22', '2022-04-23', '2022-04-24',
       '2022-04-25', '2022-04-26', '2022-04-27', '2022-04-28',
       '2022-04-29', '2022-04-30'], dtype='datetime64[D]')

16. Crea un vector ordenado de 15 elementos con valores aleatorios entre 1 y 10

In [145]:
arrayOrd = np.sort(np.random.randint(1,11,(15)))
print(arrayOrd)


array([ 1,  3,  4,  4,  4,  4,  5,  5,  5,  6,  7,  7,  8,  8, 10])

17. Devuelva la suma de los valores del vector del ejercicio anterior

In [158]:
np.sum(arrayOrd)

324

18. Devuelve el resultado de la suma del vector ejercicio 16 de una forma más rápida que utilizar np.sum

In [159]:
from functools import reduce
reduce(lambda acu,x: acu+x,arrayOrd)

324

19. Crea un vector aleatorio de tamaño 20 y reemplaza el máximo valor por 0

In [163]:
arrRand = np.random.random(20)
arrRand[arrRand == np.max(arrRand)] = 0
print(np.max(arrRand))
print(arrRand)

0.9187953785180792
[0.03636356 0.04774722 0.         0.74880601 0.80758082 0.07129794
 0.55775562 0.72686344 0.60025358 0.5118755  0.67762075 0.61736476
 0.57847206 0.10022047 0.91451155 0.54524246 0.6651577  0.91879538
 0.85508963 0.70859512]


20. Itera un numpy arrays mostrando su posición y el valor

In [5]:
array1 = np.random.randint(1,11,(10))
for i in np.ndenumerate(array1):
    print(i)

((0,), 3)
((1,), 7)
((2,), 4)
((3,), 10)
((4,), 3)
((5,), 3)
((6,), 2)
((7,), 9)
((8,), 4)
((9,), 4)


21. Resta a cada elemento la media calculada de su fila de la matriz

In [12]:
array1 = np.random.randint(1,21,(3,3))
print(array1)
print()

for i in range(len(array1)):
    array1[i] -= int(np.mean(array1[i]))

print("Resultado:")
print(array1)

[[15  7 13]
 [20  6  8]
 [ 9 12  5]]

Resultado
[[ 4 -4  2]
 [ 9 -5 -3]
 [ 1  4 -3]]


22. Crea una matriz de 6x6 y ordenala por la 4ª fila

In [16]:
array1 = np.random.randint(1,21,(6,6))
print(array1)
print()

array1[3,:] = np.sort(array1[3,:])
print(array1)

[[11 11  9 18 15 19]
 [ 2 12  3 16  8 11]
 [16 10 16  7 15  7]
 [ 4 14 14 14 20 11]
 [ 9 17  2  2 20  8]
 [ 8 12 10  2  4 14]]

[[11 11  9 18 15 19]
 [ 2 12  3 16  8 11]
 [16 10 16  7 15  7]
 [ 4 11 14 14 14 20]
 [ 9 17  2  2 20  8]
 [ 8 12 10  2  4 14]]


23. Existiendo el vector [1, 2, 3, 4, 5], construir un nuevo vector con 3 ceros consecuitovs entre cada valor del vector anterior

In [45]:
vector = np.arange(1,6)
#Se multiplica por 4 porque son 3 elementos 0 mas el elemento del vector
array1 = np.zeros(vector.size*4)

for i in range(vector.size):
    array1[i*4] = vector[i]

print(array1)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5. 0. 0. 0.]


24. Crea un vector con números aleatorios de 5x5 e intercambia la fila segunda por la tercera

In [50]:
arrRand = np.random.randint(1,50,(5,5))
print(arrRand)
print()

arrRand[1:3] = np.flipud(arrRand[1:3])
print(arrRand)

[[15 42 21 11  5]
 [20 31 46 28  2]
 [ 4 35 39 33  4]
 [ 3 10 41 10 39]
 [41 16 13 37 45]]

[[15 42 21 11  5]
 [ 4 35 39 33  4]
 [20 31 46 28  2]
 [ 3 10 41 10 39]
 [41 16 13 37 45]]
