# Cables
El problema consiste en comprobar si es posible encontrar una ordenación de cables en la cual todos ellos están conectados formando un círculo.

Cada cable tiene dos extremos y cada extremo puede ser un conectar macho (M) o hembra (H).

La conexión de un cable con otro sólo es posible juntando conectores diferentes.


### **Input**
* Un conjunto desordenado de cables representados mediante parejas de letras haciendo referencia al conector de sus extremos.

### **Output**
* Imprimir por la salida estándar "true" si es posible conectar todos los cables, "false" en caso contrario.


| Sample Input | Sample Output |
| --- | --- |
| HM | true |
| HH | false |
| HM HH MM | true |


In [73]:
def listarCables(cables):
    #Pongo el string en mayus
    cables = cables.upper()
    #Devuelvo la lista de cables separados por un espacio
    return list(cables.split())

def validacion(listaCables):
    #Le paso un listado
    for i in listaCables:
        #Si la longitud de cada array es mayor a 2 devuelvo un False
        if len(i) != 2: return False
        for x in i:
            #Si las letras no son H o M devuelvo un false
            if not (x == "H" or x == "M"): return False

    return True

def conexion(cables):
    #Inicializo la lista de cables mediante la funcion
    listaCables = listarCables(cables)

    #Si el formato es valido paso a ver las conexiones
    if validacion(listaCables):
        for i in range(len(listaCables)):
            #Si la lista solo tiene 1 posicion entro
            if len(listaCables) -1 == 0:
                #Como solo tiene una posicion miro que sean distintas las conexiones
                if listaCables[i][0] != listaCables[i][-1]: return " ".join(listaCables)+" -> True"

                return " ".join(listaCables)+" -> False"
            else:
                #Tiene mas de un elemento
                for x in range(len(listaCables[i])):
                    #Si no coincide la 1 parte del 1 elemento con la ultima parte del ultimo elemento
                    if i == 0 and listaCables[0][0] == listaCables[-1][-1]:
                        return " ".join(listaCables)+" -> False"
                    else:
                        #Si la conexion es igual al conector no se puede (False)
                        if listaCables[i][-1] == listaCables[i+1][0]: return " ".join(listaCables)+" -> False"

                return " ".join(listaCables)+" -> True"
    else:
        return "La lista de cables no es correcta. Por favor, inserte una segun el formato."

cables = input("Dime el circulo de cables: ejemplo HM HM")
print(conexion(cables))

HH MM HM -> True


# Llenando cubos
Dado un conjunto de cubos llenos de distintas cantidades de agua, se pide calcular la cantidad mínima de agua necesaria para nivelar los cubos de forma que todos ellos acaben teniendo la misma cantidad.

Consideraciones:
- El nivel de agua de un cubo no puede decrecer, sólo aumentar.
- Los cubos se nivelarán respecto al cubo más lleno.

### **Input**
* Un conjunto de números enteros especificando la cantidad de agua de la que dispone cada cubo.

### **Output**
* Imprimir por la salida estándar la cantidad mínima de agua necesaria para nivelar los cubos.

| Sample Input | Sample Output |
| --- | --- |
| 10 8 7 | 5 |
| 8 8 8  | 0 |


In [68]:
from functools import reduce

def iniLista(numCubos):
    #Si no cumple el min y el maximo de cubos no se ejecuta el resto
    if numCubos < 3 or numCubos > 6: return "Cuidado con la cantidad de cubos (Min 2, Max 6)"
    listaCubos = list()

    #Hago un bucle para hacer los input
    for i in range(numCubos):
        #Por si en el input hay otro literal que no sea de tipo int
        try:
            listaCubos.append(int(input("Dime el tamaño del cubo: ")))
        except:
            return "Los cubos tienen que ser de tipo entero, por favor introduce correctamente los parametros"

    return listaCubos

def nivelar(numCubos):
    #Inicio los cubos
    listaCubos = iniLista(numCubos)

    #Para que si da fallo devuelva el mensaje de error, y si es un lista continuar
    if type(listaCubos) is list:
        #Ordenamos por el cubo con mas cantidad
        listaCubos = sorted(listaCubos,reverse=True)
        litros = 0 #Sumador de los litros que faltan para nivelar

        #Bucle que empieza por el indice 1 porque el 0 es el elemento con mas capacidad
        for i in range(1,len(listaCubos)):
            #El sumador es la resta del elemento mas grande con el siguiente de la lista
            litros += listaCubos[0] - listaCubos[i]
        return litros
    else:
        #Devolvemos los errores de validacion de iniLista(numCubos)
        return listaCubos

try:
    numCubos = int(input("Cuantos cubos tines? (min 2, max 6)"))
    print(nivelar(numCubos))
except:
    print("Por favor, el numero de cubos tiene que ser de tipo entero...")

Por favor, el numero de cubos tiene que ser de tipo entero...


# Validación de paréntesis
Dada una cadena que contiene únicamente los caracteres ’(’, ’)’, ’{’, ’}’, ’[’ y ’]’, determinar si la cadena de entrada es válida.

### **Input**
* Los paréntesis abiertos deben cerrarse con el mismo tipo de paréntesis.
* Los paréntesis abiertos deben cerrarse en el orden correcto.

### **Output**
* Imprimir por la salida estándar "true" si la cadena es válida, "false" en caso contrario.

| Sample Input | Sample Output |
| --- | --- |
| () | true |
| () [] {} | true |
| (] | false |

In [67]:
import re

def validacion():
    #Por si hay un error en el input
    try:
        cadena = str(input("Dime una cadena de llaves con el siguiente formato de ejemplo (() {} [])"))
    except:
        raise TypeError("Error al insertar la cadena")

    #Quito los espacios para poder hacer una lista cada dos elementos
    cadenaAux = cadena.replace(" ","")
    #Aqui hago una lista cada dos elementos
    listaCadena = cadenaAux[::2]
    #Utilizo expresiones regulares para la cadena de texto
    patron = re.compile("(\\(\\)|\\{\\}|\\[\\])")
    #Con el findall obtengo una lista de las coincidencias
    listaPatron = patron.findall(cadena)

    #Si las conincidencias coinciden en las dos cadenas en longitud es que todo esta correcto
    return " ".join(cadena)+" -> True" if len(listaCadena) == len(listaPatron) else " ".join(cadena)+" -> False"

print(validacion())

( ) ( )     ( ) -> True


# Atrapando lluvia
Dados N números enteros no negativos representando un mapa de elevación, calcular cuál es el volumen de agua que queda atrapada después de llover.

### **Input**
* Una lista de números enteros en el rango 0 ≤ N ≤ 1000000 que definen la elevación del terreno en cada unidad del eje horizontal.

### **Output**
* Imprimir por la salida estándar las unidades de agua que quedan atrapadas según el mapa de elevación.

| Sample Input | Sample Output |
| --- | --- |
| 4,2,0,3,2,5 | 9 |
| 0,1,0,2,1,0,1,3,2,1,2,1  | 6 |


In [86]:
import numpy as np

#Por si queremos introducir la lista por input
'''def iniTerreno():
    #Controlo los fallos por si no es tipo entero el input
    try:
        lonTerreno = int(input("Dime la longitud del terreno"))
        #Si no cumple los requisitos
        if not (lonTerreno >= 0 and lonTerreno <= 1000000): return "La longitudo del terreno no cumple las codiciones (0 ≤ N ≤ 1000000)"
        #Si la lista es menor a 2 elementos siempre sera 0, porque no hay terreno donde acumularse el agua
        if lonTerreno < 2: return 0

        listaTerreno = list()
        #Recorro segun la longitud del terreno
        for i in range(lonTerreno):
            #Controlo los fallos por si no es tipo entero el input y lo voy almacenando en la lista
            try:
                listaTerreno.append(int(input("Dime la elevacion del terreno de la posicion {0}".format(i))))
            except:
                raise TypeError("Los elementos de la lista tienen que ser de tipo entero")

        return listaTerreno
    except:
        return "La longitud del terreno tiene que ser de tipo entero..."
'''

def obtMax(lista):
    if type(lista) is list:
        return sorted(lista,reverse=True)[0]
    else:
        raise TypeError("El parametro tiene que ser una lista...")


def generarArrayBi(lista):
    altura = obtMax(lista)
    mapa = np.zeros((altura,len(lista)), dtype=int)

    for i in range(len(lista)):
        if lista[i] > 0:
            for x in range(lista[i]):
                mapa[x][i] = 9

    return mapa

def pintarMapa(array):
    mapa = array

    for i in reversed(range(len(array))):
        print(array[i])

def calcLluvia(mapaTerreno):
    #Inicializo la lista terreno, que nos puede devolver 3 tipos (lista, entero, string)
    #listaTerreno = iniTerreno()
    #Genero el mapa
    #mapaTerreno = generarArrayBi(listaTerreno)

    for i in range(len(mapaTerreno)):
        for x in range(len(mapaTerreno[i])):
            #Si encuentra una celda que tiene terreno compara para llenar de agua
            if mapaTerreno[i][x] != 0:
                entra = False

                #Si la celda de x+1 al final no tiene ningun 9 no entra en el otro for
                for y in range(x+1, len(mapaTerreno[i])):
                    if mapaTerreno[i][y] == 9:
                        entra = True
                        break

                if entra:
                    for x2 in range(x+1,len(mapaTerreno[i])):
                        if mapaTerreno[i][x2] == 9:
                            break
                        else:
                            mapaTerreno[i][x2] = 1

    pintarMapa(mapaTerreno)
    return np.count_nonzero(mapaTerreno == 1)


lista = [0,1,0,2,1,0,1,3,2,1,2,1]

array = generarArrayBi(lista)
print("Terreno generado")
pintarMapa(array)
print()

print("Terreno final")
valor = calcLluvia(array)
print()
print("{0} -> {1}".format(lista,valor))




Terreno generado
[0 0 0 0 0 0 0 9 0 0 0 0]
[0 0 0 9 0 0 0 9 9 0 9 0]
[0 9 0 9 9 0 9 9 9 9 9 9]

Terreno final
[0 0 0 0 0 0 0 9 0 0 0 0]
[0 0 0 9 1 1 1 9 9 1 9 0]
[0 9 1 9 9 1 9 9 9 9 9 9]

[0, 1, 0, 2, 1, 0, 1, 3, 2, 1, 2, 1] -> 6


# Juego de saltos
Dada una lista de enteros no negativos de longitud L, comienzas en la posición del primer índice de la lista. Cada elemento de la lista, con valor N, representa la longitud máxima de salto en esa posición. Tu objetivo es llegar al último índice en el mínimo número de saltos.

Nota: Puedes asumir que siempre es posible llegar al último índice.

### **Input**
* 1 <= L <= 100000
* 1 <= N <= 1000

### **Output**
* Imprimir por la salida estándar el mínimo numero de saltos necesarios para llegar al último índice

| Sample Input | Sample Output |
| --- | --- |
| [2,3,1,1,4]  | 2 |
| [2,3,0,1,4] | 2 |

# Matriz Espiral
Dada una matriz m x n, devuelve todos los elementos de la matriz ordenados en forma de espiral.

### **Input**
* m == matriz.length
* n == matriz[i].length
* 1 <= m, n <= 10
* -100 <= matriz[i][j] <= 100

### **Output**
* Imprimir por la salida estándar el array resultante

| Sample Input | Sample Output |
| --- | --- |
| [[1,2,3], [4,5,6], [7,8,9]]   | [1,2,3,6,9,8,7,4,5] |
| [[1,2,3,4], [5,6,7,8], [9,10,11,12]] | [1,2,3,4,8,12,11,10,9,5,6,7] |

# Subiendo escaleras
Estás subiendo una escalera de N escalones.

Con cada paso puedes subir 1 o 2 escalones. ¿De cuántas maneras diferentes puedes subir la escalera?

### **Input**
* Un número entero 1 ≤ N ≤ 45 indicando el número de escalones de la escalera.

### **Output**
* Imprimir por la salida estándar el número de formas diferentes que existen para subir la escalera.

| Sample Input | Sample Output |
| --- | --- |
| 2 | 2 |
| 3 | 3 |


# Máximo beneficio
Se proporciona una lista de precios de stock en días consecutivos, de manera que el elemento en posición i es el precio del stock en el día i.

Calcular el máximo beneficio resultado de comprar un stock en un único día del listado y venderlo en un día posterior.

### **Input**
* Una lista de números enteros 0 ≤ N ≤ 1000 que define el precio del stock en cada día.

### **Output**
* Imprimir por la salida estándar el máximo beneficio que puede obtenerse con la transacción. Si no es posible obtener beneficio, imprimir 0.

| Sample Input | Sample Output |
| --- | --- |
| 7,1,5,3,6,4 | 5 |
| 7,6,4,3,1 | 0 |