In [2]:
import numpy as np

#Obtener informacion de un metodo np
np.info(np.less)

less(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Return the truth value of (x1 < x2) element-wise.

Parameters
----------
x1, x2 : array_like
    Input arrays.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the defa

In [5]:
#Comprobar si todos los elementos del array son verdaderos
a = np.ones(5)
b = np.zeros(5)
b[2] = 1

print(np.all(a))
print(np.all(b))

#Comprobar si algun de los elementos del array es verdadero
print(np.any(b))

True
False
True


In [8]:
a = np.array([1,6,7])
b = np.flip(a) #Invertir array

#Menor que
print(np.less(a,b))
#Menor igual que
print(np.less_equal(a,b))

#Mayor que
print(np.greater(a,b))
#Mayor igual que
print(np.greater_equal(a,b))

[ True False False]
[ True  True False]
[False False  True]
[False  True  True]


In [20]:
#Crear array con un rango numerico
print(np.arange(1,23))

#Crear array con un rango numerico con saltos
print(np.arange(0,23,2))

#Crear array aleatorios
print(np.random.randint(0,20,(3,3)))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22]
[ 0  2  4  6  8 10 12 14 16 18 20 22]
[[ 9  6  6]
 [ 5 15 17]
 [ 6  7 10]]


In [14]:
#Crear matriz de identeidad
print("Matriz de identidad")
print(np.identity(3))
print()

#Obtener la diagonal del array
print("Diagonal del array")
a = np.arange(9).reshape(3,3)
print(np.diag(a,1))
print()

#Obtener filas y columnas del array
print("Filas y columnas")
print(a.shape)
print()

#Crear una diagonal con cualquier numero
print("Diagonal con cualquier numero")
numero = 6
a = np.zeros((3,3))
np.fill_diagonal(a,numero)
print(a)
print()

#Invertir orden columnas
print("Invertir una diagonal")
b = a
b = np.fliplr(b)
print(b)
print()

#Crear diagonal a paritr de una numeracion
a = np.diagflat(np.arange(1,4))
print("Diagonal a partir de una matriz")
print(a)

#Invertir orden filas
print("Invertir diagonal en filas")
c = a
c = np.flipud(c)
print(c)
print()




Matriz de identidad
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Diagonal del array
[1 5]

Filas y columnas
(3, 3)

Diagonal con cualquier numero
[[6. 0. 0.]
 [0. 6. 0.]
 [0. 0. 6.]]

Invertir una diagonal
[[0. 0. 6.]
 [0. 6. 0.]
 [6. 0. 0.]]

Diagonal a partir de una matriz
[[1 0 0]
 [0 2 0]
 [0 0 3]]
Invertir diagonal en filas
[[0 0 3]
 [0 2 0]
 [1 0 0]]



In [19]:
a = np.diagflat(np.arange(1,4))
print("Diagonal a partir de una matriz")
print(a)
print()
print(np.fliplr(a))
print()
print()
print(np.flipud(a))
print()
print()
print(np.flipud(np.fliplr(a)))
print()

Diagonal a partir de una matriz
[[1 0 0]
 [0 2 0]
 [0 0 3]]

[[0 0 1]
 [0 2 0]
 [3 0 0]]


[[0 0 3]
 [0 2 0]
 [1 0 0]]


[[3 0 0]
 [0 2 0]
 [0 0 1]]

